from . import test_call_price
from . import test_insta_post
from . import test_insta_profile
from . import test_portal_dashboard_data
from . import test_product_product
from . import test_product_template
from . import test_res_config_settings
from . import test_sale_order
from . import test_sale_return
from . import test_stock_picking
from . import test_stock_return_picking
from . import test_website
from . import test_all_in_one_website_kit
from . import test_main
from . import test_portal
from . import test_website_sale