# Generated by Django 5.0.6 on 2026-06-17 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='odoocredential',
            name='name',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='odoocredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odoo_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
